name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy over SSH
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/app || mkdir ~/app && cd ~/app
          git clone https://github.com/Viraj-1110/Travifai_project.git || true
          cd Travifai_project
          git pull origin main

          # Stop & remove old container
          sudo docker stop travifai_project || true
          sudo docker rm travifai_project || true

          # Build & run new container
          sudo docker build -t travifai_project:v.1 .
          sudo docker run -dit -p 8080:80 --name travifai_project travifai_project:v.1

          # Save logs locally
          mkdir -p ~/app/logs
          sudo docker logs travifai_project > ~/app/logs/container.log 2>&1

          # Upload logs to S3 (uses your existing AWS CLI config on EC2)
          aws s3 cp ~/app/logs/container.log s3://travifai-project-logs/Project-logs/container-$(date +%F-%T).log
